const SHORT_DURATION = 40
const INITIAL_MOVIES_QTY = {
  MOBILE: 5,
  TABLET: 8,
  DESKTOP: 12,
}
const ITEMS_PER_ROW = {
  MOBILE: 1,
  TABLET: 2,
  DESKTOP: 3,
}
const SCREEN_WIDTH = {
  MOBILE: 320,
  TABLET: 480,
  DESKTOP: 800,
}

export { SHORT_DURATION, SCREEN_WIDTH, INITIAL_MOVIES_QTY, ITEMS_PER_ROW }
